[profile.default]
src = 'forge'
out = 'artifacts-forge'
cache_path  = 'cache-forge'
libs = ['node_modules']
remappings = [
    '@chainlink/=node_modules/@chainlink/',
    '@openzeppelin-2/=node_modules/@openzeppelin-2/',
    '@openzeppelin-4/=node_modules/@openzeppelin-4/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    'forge-std/=node_modules/forge-std/src',
    'ds-test/=node_modules/ds-test/src'
]
# libraries = []
# cache = true
# force = true
# evm_version = 'london'
# gas_reports = ['*']
## Sets the concrete solc version to use, this overrides the `auto_detect_solc` value
# solc_version = '0.8.10'
auto_detect_solc = true
# offline = false
optimizer = true
optimizer_runs = 200
verbosity = 2
# ignored_error_codes = []
# fuzz_runs = 256
# ffi = false
# sender = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
# tx_origin = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
# initial_balance = '0xffffffffffffffffffffffff'
# block_number = 0
# gas_limit = 9223372036854775807
# gas_price = 0
# block_base_fee_per_gas = 0
# block_coinbase = '0x0000000000000000000000000000000000000000'
# block_timestamp = 0
# block_difficulty = 0

# These^ are all the available config options
# Docs at https://github.com/gakonst/foundry/tree/master/config

[rpc_endpoints]
eth = "${ETH_RPC}"
mainnet = "${ETH_RPC}"
ethereum = "${ETH_RPC}"
optimism = "${OPTIMISM_RPC}"
arbitrum = "${ARBITRUM_RPC}"
bsc = "${BSC_RPC}"